name: ecart
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  cached_network_image: ^3.3.0
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  firebase_auth: ^4.14.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/